"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

#import django.core.context_processors.media

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7u0%8v8&2p-eg(-9(q*$tv!z6pcy*$sf^h6l_$a2z9(!3+)*lx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

ALLOWED_HOSTS = ['*']


SESSION_COOKIE_DOMAIN = '.kuvalda.lv'
SESSION_COOKIE_NAME = 'kuvaldasessionid'

#Handle session is not Json Serializable
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_COOKIE_AGE = 5 * 60 #

# Auto logout delay in minutes
AUTO_LOGOUT_DELAY = 240

# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# my app's
    'kamera',
    'galerija',

    'animal',
    'loginsys',
    'statistic',

# MAPPlot
    'mapplot',

# mobile
    'mobile',
# REST API
    'rest_framework',
#    'rest_framework.authtoken',
#    'rest_auth',
# DJANGO CLEANUP FOR MEDIA

# GCM
    'gcm',
    'django_cleanup', # MEDIA FILES DELETE /SHOULD BE AT THE END/

    'django_user_agents',
)

#GCM
GCM_APIKEY = "trailcamphoto-179317"

# RESR Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
#        'rest_framework.authentication.SessionAuthentication',
#        'rest_framework.authentication.TokenAuthentication',
    ),

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
#        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

#    'DEFAULT_PARSER_CLASSES': (
#        'rest_framework.renderers.JSONParser',
#    ),
    'DEFAULT_PERMISSION_CLASSES': [
#        'rest_framework.permissions.IsAdminUser',
        'rest_framework.permissions.IsAuthenticated',
    ],
    'PAGE_SIZE': 5
}



MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
# Auto logout after 60 min
    'main.last_seen.AutoLogout',
# FOR LAST SEEN MIDLEWARE CLASS
    'main.last_seen.SetLastVisitMiddleware',
#    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
)

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
		'/home/svabis/web/template',
		'/home/svabis/web/kamera/template',
		'/home/svabis/web/loginsys/template',
		'/home/svabis/web/galerija/template',
		'/home/svabis/web/mapplot/template',
#		'/www/kuvalda/template',
#		'/www/kuvalda/galerija/template',
#		'/www/kuvalda/kamera/template',
#		'/www/kuvalda/loginsys/template',
#		'/www/kuvalda/mapplot/template',
		],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
#	'OPTIONS': {'charset': 'utf8mb4'},	# LV support, need python upgrade
        'NAME': 'kuvalda_db',
        'USER': 'kuvalda_web',
        'PASSWORD': 'kuv@ld@_WEB!',
#        'HOST': 'localhost',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#DEFAULT_CHARSET = 'utf-8' # added for Latvian queries in Admin

LANGUAGE_CODE = 'lv' #'en-us'

TIME_ZONE = 'Europe/Riga' #'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#USE_UNICODE = True	# for unicode support

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


STATICFILES_DIRS = (
#    os.path.join(BASE_DIR, "static"),
#    '/kuvalda/static/',
#    '/kuvalda/kamera/static/',
)


#STATIC_ROOT = '/home/svabis/web/static/'
STATIC_ROOT = '/www/kuvalda/static/'
STATIC_URL = '/static/'


#MEDIA_ROOT = '/home/svabis/web/media/'
MEDIA_ROOT = '/www/kuvalda/media/'
MEDIA_URL = '/media/'
